/* 관리자 */
CREATE TABLE ADMIN (
	AD_NO NUMBER NOT NULL, /* 관리자번호 */
	AD_ID VARCHAR2(50) NOT NULL, /* 관리자아이디 */
	AD_PWD VARCHAR2(50) NOT NULL, /* 관리자비밀번호 */
	AD_NICK VARCHAR2(50) NOT NULL /* 관리자닉네임 */
);

ALTER TABLE ADMIN
	ADD
		CONSTRAINT PK_ADMIN
		PRIMARY KEY (
			AD_ID
		);
CREATE SEQUENCE ADMIN_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;
