/* 정산 내역 */
CREATE TABLE BALANCING (
	B_NO NUMBER NOT NULL, /* 정산번호 */
	C_NO NUMBER NOT NULL, /* 클래스코드 */
	H_NO NUMBER NOT NULL, /* 호스트번호 */
	B_PPNUM NUMBER, /* 진행인원 */
	B_REQ_DATE DATE, /* 정산신청일 */
	B_FLAG VARCHAR2(10) DEFAULT N /* 정산신청여부 */
);

ALTER TABLE BALANCING
	ADD
		CONSTRAINT PK_BALANCING
		PRIMARY KEY (
			B_NO
		);

ALTER TABLE BALANCING
	ADD
		CONSTRAINT FK_HOSTCLASS_TO_BALANCING
		FOREIGN KEY (
			C_NO
		)
		REFERENCES HOSTCLASS (
			C_NO
		);

ALTER TABLE BALANCING
	ADD
		CONSTRAINT FK_HOST_TO_BALANCING
		FOREIGN KEY (
			H_NO
		)
		REFERENCES HOST (
			H_NO
		);
        
CREATE SEQUENCE BALANCING_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        