/* 참여제한회원 */
CREATE TABLE BAN (
	BNO NUMBER NOT NULL, /* 제한번호 */
	HNO NUMBER, /* 호스트번호 */
	M_NO NUMBER NOT NULL, /* 개인회원번호 */
	BCS VARCHAR2(50), /* 제한사유분류 */
	BC VARCHAR2(4000), /* 상세내용 */
	REGDATE DATE /* 등록일 */
);

ALTER TABLE BAN
	ADD
		CONSTRAINT PK_BAN
		PRIMARY KEY (
			BNO
		);

ALTER TABLE BAN
	ADD
		CONSTRAINT FK_MEMBER_TO_BAN
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

ALTER TABLE BAN
	ADD
		CONSTRAINT FK_HOST_TO_BAN
		FOREIGN KEY (
			HNO
		)
		REFERENCES HOST (
			H_NO
		);

CREATE SEQUENCE BAN_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        