/* 블랙리스트 */
CREATE TABLE BLACKLIST (
	BNO NUMBER NOT NULL, /* 블랙리스트번호 */
	M_NO NUMBER, /* 개인회원번호 */
	HNO NUMBER, /* 호스트번호 */
	REGDATE DATE NOT NULL, /* 등록일 */
	COL VARCHAR2(10), /* 구분플래그 */
	DELFLAG VARCHAR2(10) NOT NULL /* 삭제플래그 */
);

ALTER TABLE BLACKLIST
	ADD
		CONSTRAINT PK_BLACKLIST
		PRIMARY KEY (
			BNO
		);

ALTER TABLE BLACKLIST
	ADD
		CONSTRAINT FK_MEMBER_TO_BLACKLIST
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

ALTER TABLE BLACKLIST
	ADD
		CONSTRAINT FK_HOST_TO_BLACKLIST
		FOREIGN KEY (
			HNO
		)
		REFERENCES HOST (
			H_NO
		);