/* 수강내역 */
CREATE TABLE C_LIST (
	PLCODE NUMBER NOT NULL, /* 수강번호 */
	M_NO NUMBER NOT NULL, /* 개인회원번호 */
	C_NO NUMBER NOT NULL, /* 클래스코드 */
	QTY NUMBER NOT NULL, /* 수량 */
	TOTAL NUMBER NOT NULL, /* 결제금액 */
	P_DAY DATE NOT NULL /* 결제일 */
);

ALTER TABLE C_LIST
	ADD
		CONSTRAINT PK_C_LIST
		PRIMARY KEY (
			PLCODE
		);

ALTER TABLE C_LIST
	ADD
		CONSTRAINT FK_MEMBER_TO_C_LIST
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

ALTER TABLE C_LIST
	ADD
		CONSTRAINT FK_HOSTCLASS_TO_C_LIST
		FOREIGN KEY (
			C_NO
		)
		REFERENCES HOSTCLASS (
			C_NO
		);
        
CREATE SEQUENCE C_LIST_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        