/* 카테고리 */
CREATE TABLE CATEGORY (
	CATEGORY_CODE NUMBER NOT NULL, /* 카테고리코드 */
	CATEGORY_NAME VARCHAR(100) NOT NULL /* 카테고리이름 */
);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			CATEGORY_CODE
		);