/* 호스트회원 */
CREATE TABLE HOST (
	H_NO NUMBER NOT NULL, /* 호스트번호 */
	H_GRADE VARCHAR2(30) NOT NULL, /* 호스트등급명 */
	H_NAME VARCHAR(50) NOT NULL, /* 업체명 */
	H_ID VARCHAR(50) NOT NULL, /* 아이디 */
	H_PWD VARCHAR(100) NOT NULL, /* 비밀번호 */
	H_EMAIL VARCHAR(100) NOT NULL, /* 이메일 */
	H_PHONE VARCHAR(30) NOT NULL, /* 전화번호 */
	H_BUSINESS_NUM VARCHAR2(255), /* 사업자번호 */
	H_ADDRESS VARCHAR(200) NOT NULL, /* 업체주소 */
	REGDATE DATE DEFAULT SYSDATE /* 가입일 */
);

ALTER TABLE HOST
	ADD
		CONSTRAINT PK_HOST
		PRIMARY KEY (
			H_NO
		);

ALTER TABLE HOST
	ADD
		CONSTRAINT FK_H_GRADE_TO_HOST
		FOREIGN KEY (
			H_GRADE
		)
		REFERENCES H_GRADE (
			H_GRADE
		);

CREATE SEQUENCE HOST_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;