/* 클래스 */
CREATE TABLE HOSTCLASS (
	C_NO NUMBER NOT NULL, /* 클래스코드 */
	C_NAME VARCHAR(100) NOT NULL, /* 클래스명 */
	CATEGORY_CODE NUMBER NOT NULL, /* 카테고리코드 */
	H_NO NUMBER NOT NULL, /* 호스트번호 */
	L_NO NUMBER, /* 장소번호 */
	C_PRICE NUMBER NOT NULL, /* 가격 */
	PPNUM NUMBER, /* 진행인원 */
	C_REGDATE DATE DEFAULT SYSDATE, /* 등록일 */
	C_START_TIME DATE NOT NULL, /* 시작일 */
	END_FLAG VARCHAR2(20), /* 종료여부 */
	C_TIME NUMBER, /* 시작시간 */
	FPNUM NUMBER /* 확정인원 */
);

ALTER TABLE HOSTCLASS
	ADD
		CONSTRAINT PK_HOSTCLASS
		PRIMARY KEY (
			C_NO
		);

ALTER TABLE HOSTCLASS
	ADD
		CONSTRAINT FK_HOST_TO_HOSTCLASS
		FOREIGN KEY (
			H_NO
		)
		REFERENCES HOST (
			H_NO
		);

ALTER TABLE HOSTCLASS
	ADD
		CONSTRAINT FK_CATEGORY_TO_HOSTCLASS
		FOREIGN KEY (
			CATEGORY_CODE
		)
		REFERENCES CATEGORY (
			CATEGORY_CODE
		);

ALTER TABLE HOSTCLASS
	ADD
		CONSTRAINT FK_LOCATION_TO_HOSTCLASS
		FOREIGN KEY (
			L_NO
		)
		REFERENCES LOCATION (
			L_NO
		);
        
CREATE SEQUENCE HOSTCLASS_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        