/* 클래스장소 */
CREATE TABLE LOCATION (
	L_NO NUMBER NOT NULL, /* 장소번호 */
	ZIPCODE VARCHAR(10) NOT NULL, /* 우편번호 */
	L_ADDRESS VARCHAR(300) NOT NULL, /* 주소 */
	L_ADDRESS_DETAIL VARCHAR2(300) NOT NULL, /* 상세주소 */
	H_NO NUMBER /* 호스트번호 */
);

ALTER TABLE LOCATION
	ADD
		CONSTRAINT PK_LOCATION
		PRIMARY KEY (
			L_NO
		);

ALTER TABLE LOCATION
	ADD
		CONSTRAINT FK_HOST_TO_LOCATION
		FOREIGN KEY (
			H_NO
		)
		REFERENCES HOST (
			H_NO
		);
        
CREATE SEQUENCE LOCATION_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        