/* 개인회원 */
CREATE TABLE MEMBER (
	M_NO NUMBER NOT NULL, /* 개인회원번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 이메일아이디 */
	M_NAME VARCHAR2(50), /* 이름 */
	PWD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	M_NICKNAME VARCHAR2(50), /* 닉네임 */
	PHONE VARCHAR2(30), /* 휴대전화 */
	BDAY DATE, /* 생년월일 */
	M_ZIPCODE VARCHAR2(50), /* 우편번호 */
	M_ADDRESS VARCHAR2(200), /* 주소 */
	M_ADRESS_DETAIL VARCHAR2(200), /* 주소상세 */
	REGDATE DATE DEFAULT SYSDATE, /* 가입일 */
	M_GRADE VARCHAR2(50) DEFAULT silver, /* 회원등급명 */
	M_ORIGINALNAME VARCHAR2(200), /* 프로필원본파일명 */
	M_FILESIZE NUMBER, /* 파일사이즈 */
	M_FILENAME VARCHAR2(200), /* 업로드파일명 */
	DELFLAG VARCHAR2(10) DEFAULT N, /* 탈퇴플래그 */
	M_BAN_FLAG VARCHAR2(20), /* 참여제한플래그 */
	M_BLACKLIST_FLAG VARCHAR2(20) /* 블랙리스트플래그 */
);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			M_NO
		);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT FK_U_GRADE_TO_MEMBER
		FOREIGN KEY (
			M_GRADE
		)
		REFERENCES U_GRADE (
			M_GRADE
		);
        
CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        