/* 쪽지보관함 */
CREATE TABLE NOTE_REC (
	REC_NO NUMBER NOT NULL, /* 보관함번호 */
	NOTE_NO NUMBER, /* 쪽지번호 */
	M_NO NUMBER NOT NULL, /* 받는회원번호 */
	REC_DELFALG VARCHAR2(10) NOT NULL, /* 삭제여부 */
	REC_IMPFLAG VARCHAR2(10) NOT NULL, /* 중요쪽지여부 */
	REC_READFLAG VARCHAR2(50) NOT NULL /* 읽음여부 */
);

ALTER TABLE NOTE_REC
	ADD
		CONSTRAINT PK_NOTE_REC
		PRIMARY KEY (
			REC_NO
		);

ALTER TABLE NOTE_REC
	ADD
		CONSTRAINT FK_NOTE_TO_NOTE_REC
		FOREIGN KEY (
			NOTE_NO
		)
		REFERENCES NOTE (
			NOTE_NO
		);

ALTER TABLE NOTE_REC
	ADD
		CONSTRAINT FK_MEMBER_TO_NOTE_REC
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);
        
CREATE SEQUENCE NOTE_REC_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;