/* 쪽지함 */
CREATE TABLE NOTE (
	NOTE_NO NUMBER NOT NULL, /* 쪽지번호 */
	M_ID VARCHAR2(50), /* 아이디 */
	R_NICKNAME VARCHAR2(50), /* 닉네임 */
	NOTE_TITLE VARCHAR2(100) NOT NULL, /* 제목 */
	NOTE_CONTENT CLOB NOT NULL, /* 내용 */
	NOTE_REGDATE DATE NOT NULL, /* 전송일 */
	NOTE_DELFALG VARCHAR2(10) /* 삭제여부 */
);

ALTER TABLE NOTE
	ADD
		CONSTRAINT PK_NOTE
		PRIMARY KEY (
			NOTE_NO
		);
CREATE SEQUENCE NOTE_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        