/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_NO NUMBER NOT NULL, /* 공지사항번호 */
	NOTICE_TITLE VARCHAR2(255) NOT NULL, /* 제목 */
	NOTICE_CONTENT VARCHAR2(4000) NOT NULL, /* 내용 */
	NOTICE_REGDATE DATE DEFAULT SYSDATE, /* 작성일 */
	NOTICE_STEP NUMBER, /* 단계 */
	NOTICE_GROUP_ID NUMBER, /* 그룹넘버 */
	NOTICE_FLAG VARCHAR2(5) DEFAULT 'N' NOT NULL, /* 공지사항분류 */
	NOTICE_READCOUNT NUMBER, /* 조회수 */
	NOTICE_IMG_URL VARCHAR2(4000) /* 공지사항 이미지 */
);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_NO
		);
        
CREATE SEQUENCE NOTICE_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;