/* 결제내역 */
CREATE TABLE ORDERS (
	MERCHANT_UID VARCHAR2(100) NOT NULL, /* 영수증번호 */
	C_NO NUMBER, /* 클래스코드 */
	M_NO NUMBER, /* 개인회원번호 */
	PAY_DATE DATE, /* 결제일시 */
	PRICE NUMBER, /* 결제금액 */
	REFUND VARCHAR2(50), /* 환불여부 */
	EA NUMBER, /* 결제수량 */
	IMP_UID VARCHAR2(100), /* 결제점번호 */
	F_DATE DATE, /* 결제확정일자 */
	F_TIME NUMBER /* 결제확정일시 */
);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT PK_ORDERS
		PRIMARY KEY (
			MERCHANT_UID
		);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT FK_HOSTCLASS_TO_ORDERS
		FOREIGN KEY (
			C_NO
		)
		REFERENCES HOSTCLASS (
			C_NO
		);

ALTER TABLE ORDERS
	ADD
		CONSTRAINT FK_MEMBER_TO_ORDERS
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);

CREATE SEQUENCE ORDERS_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        