/* 불편사항 */
CREATE TABLE RECOMMENDATION (
	RECO_NO NUMBER NOT NULL, /* 건의번호 */
	M_NO NUMBER, /* 개인회원번호 */
	RECO_TITLE VARCHAR2(200) NOT NULL, /* 제목 */
	RECO_PWD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	RECO_CONTENT CLOB NOT NULL, /* 내용 */
	REGDATE DATE DEFAULT SYSDATE NOT NULL, /* 등록일 */
	FLAG VARCHAR2(10), /* 삭제플래그 */
	GROUP_NO NUMBER, /* 그룹번호 */
	STEP NUMBER, /* 단계번호 */
	SROT_NO NUMBER, /* 분류번호 */
	M_ID VARCHAR2(50), /* 이메일아이디 */
	H_ID VARCHAR(50) /* 아이디 */
);

ALTER TABLE RECOMMENDATION
	ADD
		CONSTRAINT PK_RECOMMENDATION
		PRIMARY KEY (
			RECO_NO
		);

ALTER TABLE RECOMMENDATION
	ADD
		CONSTRAINT FK_MEMBER_TO_RECOMMENDATION
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);
CREATE SEQUENCE RECOMMENDATION_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        