/* 클래스후기 */
CREATE TABLE REVIEW (
	R_NO NUMBER NOT NULL, /* 후기번호 */
	C_NO NUMBER, /* 클래스코드 */
	H_NO NUMBER, /* 호스트번호 */
	M_NO NUMBER, /* 개인회원번호 */
	R_RATE NUMBER, /* 평점 */
	R_CONTENT NCLOB, /* 리뷰내용 */
	R_UPLOADNAME VARCHAR2(255), /* 업로드파일명 */
	R_FILESIZE NUMBER, /* 파일사이즈 */
	R_ORIGINALNAME VARCHAR2(255), /* 원본파일명 */
	R_REGDATE DATE DEFAULT SYSDATE, /* 등록일 */
	NICKNAME VARCHAR2(50) /* 작성자닉네임 */
);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			R_NO
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_HOSTCLASS_TO_REVIEW
		FOREIGN KEY (
			C_NO
		)
		REFERENCES HOSTCLASS (
			C_NO
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_HOST_TO_REVIEW
		FOREIGN KEY (
			H_NO
		)
		REFERENCES HOST (
			H_NO
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_REVIEW
		FOREIGN KEY (
			M_NO
		)
		REFERENCES MEMBER (
			M_NO
		);
CREATE SEQUENCE REVIEW_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;        